### ISSUE TITLE
Sharing single notes with other users

### ISSUE THREAD

**Issue by nomeata** [cweiske/grauphel#50]
I am running an owncloud instance for my family, and I am looking for a note synchronization solution that would allow me to share selected notes with other users or group of users, just like I can share files on owncloud. Judging from the screenshots grauphel does not support that. If that is correct, consider this a kind feature request.

**Comment by cweiske** [comment]
No, this is not possible at the moment. I also do not plan to implement this. If someone comes up with a patch I'll happily merge it.

**Comment by joshp23** [comment]
I like this idea, especially since there are already various links available for exporting (html, json, etc.). I don't know Own/Next Cloud very well, but it seems as if creating a share button relative to the existing buttons shouldn't be to bad...

Incidentally, while I like the html, etc. links, is there an intended purpose for these, other than a nice proof of concept?

**Comment by cweiske** [comment]
## Sharing notes with other users on the same instance

This must not only work on the web interface, but also sync the shared notes to their tomboy/tomdroid/.. clients.

- For this to work, the SQL data structure would need to be modified to allow assigning a note to several users.
- Synchronization would need to be adjusted, so that when user A syncs the note, the sync revision of user B needs to be incremented
- A share configuration would be needed. This could be solely in the web interface, or tags/categories could be used for this (`shared-with-$username`)

## Download links
The download links are for manual exporting. Initially I thought there could be a auto-sync-to-files (html or rst) into the nextcloud file system (even two-way: changing the rst file on your nextcloud-shared folder on your desktop would sync to your note in tomdroid), but I never needed this enough to implement it.

**Comment by joshp23** [comment]
It seems like view only shares might work with the export links? I would like to explore this. Grad school is about to start up, so I don't know when, but this will be  on my radar...

**Comment by cweiske** [comment]
Closing this since I won't be implementing it.
