### ISSUE TITLE
Nextcloud 13

### ISSUE THREAD

**Issue by fredscud** [cweiske/grauphel#54]
Hi,
trying to enable the app : 

` [Exception]
  App "Grauphel: Tomboy note server" cannot be installed because it is not co
  mpatible with this version of the server.`

Thanks,
Fred.

**Comment by cweiske** [comment]
Yes, this is that way because I did not test on NC 13 yet.
You could help by trying the version on NC13 yourself:

1. Download the `.tar.gz` file from http://cweiske.de/grauphel.htm#download
2. Extract it in your `nextcloud/apps/` directory
3. Adjust `appinfo/info.xml` to have a nextcloud `max-version` of 13
4. Enable grauphel in the nextcloud apps manager
5. Test it
6. Report back, so that I can either fix the issues you found or increase the max version and re-release grauphel.

**Comment by fredscud** [comment]
I have adjusted `appinfo/info.xml` to have a nextcloud `max-version` of 13.
The app is now enabled.
I have tested with Tomdroid. 
Authentication OK
I have created a note on Tomdroid - Synchro OK
I have installed Tomboy on an Ubuntu 16.04 station - Synchro OK.
Everything seems to be OK. Do you want me more tests?

**Comment by cweiske** [comment]
No, that looks fine. Thank you!

**Comment by cweiske** [comment]
The nextcloud app store now contains 0.6.7 that is marked as compatible with nextcloud 13: https://apps.nextcloud.com/apps/grauphel
